/**
 * Root Layout Component
 * 
 * Next.js App Router root layout that wraps all pages.
 * Sets up fonts, metadata, and global HTML structure.
 * 
 * @module RootLayout
 */

import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

/**
 * Geist Sans font configuration
 * Primary font for the application
 */
const geistSans = Geist({
  variable: "--font-geist-sans", // CSS variable name
  subsets: ["latin"], // Character subsets to include
});

/**
 * Geist Mono font configuration
 * Monospace font for code/technical content
 */
const geistMono = Geist_Mono({
  variable: "--font-geist-mono", // CSS variable name
  subsets: ["latin"], // Character subsets to include
});

/**
 * Page metadata
 * Used for SEO and browser tab information
 */
export const metadata: Metadata = {
  title: "Create Next App", // TODO: Update to "Virtual Office"
  description: "Generated by create next app", // TODO: Update with app description
};

/**
 * Root Layout Component
 * 
 * Wraps all pages in the application with fonts and HTML structure
 * 
 * @param {Object} props - Component props
 * @param {React.ReactNode} props.children - Child components (pages)
 * @returns {JSX.Element} Root HTML structure
 */
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        {children}
      </body>
    </html>
  );
}
